spring.application.name=demo

# URL de conexão: altera "cyber_tycoon_db" para o nome do banco que você criou no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/cyber_tycoon_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate / JPA Configurações
# 'update' cria ou atualiza as tabelas no banco de dados automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true